wtfblog/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/newpost/', views.PostCreateView.as_view(), name='post_create'),

    path('post/<int:pk>/editpost/',
         views.PostUpdateView.as_view(), name='post_update'),

    path('post/<int:pk>/removepost/',
         views.PostDeleteView.as_view(), name='post_delete'),

    path('drafts/', views.DraftListView.as_view(), name='post_drafts'),
    path('post/<int:pk>/publish/', views.publish_post, name='post_publish'),
    path('post/<int:pk>/comment/', views.add_comment, name='adding_comment'),

    path('comment/<int:pk>/approving/',
         views.approving_comment, name='approve_comment'),

    path('comment/<int:pk>/removing/',
         views.remove_comment, name='remove_comment'),
]

wtfblog/wtfblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login', views.LoginView.as_view(), name='login'),
    path('accounts/logout', views.LogoutView.as_view(),
         name='logout', kwargs={'next_page': '/'}),
]

wtfblog/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.


# Model for Posting something on blog
class Post(models.Model):
    #  one user or multiple usersie the super user. thats why we are using auth.User
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

# published date can either be left empty or none or when published get the current date use the below method
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comment(self):
        return self.comments.filter(approved_comment=True)

    # after posting the blog returns to the blog

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


# Model for Commenting something on blog
class Comments(models.Model):
    # to post a comment, inherit the Post class u can either use blog.Post or just Post
    # reason for blog.Post is its more explicit ie clear and clean than implicit and the blog comes from the app name in app.py
    post = models.ForeignKey(
        'blog.Post', related_name='comments', on_delete=models.CASCADE)
    # random user without any need of credintials
    user = models.CharField(max_length=20)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())

    # this is not approved by default and it goes back to approve_comment() in Post where it only show approved_comment= True
    approved_comment = models.BooleanField(default=False)

    # for making approved_comment= True
    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.user

wtfblog/blog/forms.py
from django import forms
from .models import Post, Comments


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('user', 'title', 'body')

        # this is how to create widgets that will correspond to css using class
        # field which will have the field type which will have attributes ie attrs which will have class
        widgets = {
            'title': forms.TextInput(attrs={'class': 'posttitleclass'}),
            'body': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontentclass'}),
        }
        # in body the class postcontentclass is the class we defined or we made
        # editable medium-editor-textarea is a class which we are gonna prob do is pip install it
        # ie it is from external source


class CommentsForm(forms.ModelForm):

    class Meta():
        model = Comments
        fields = ('user', 'body')

        widgets = {
            'user': forms.TextInput(attrs={'class': 'posttitleclass'}),
            'body': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

wtfblog/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from blog.models import Comments, Post
from blog.forms import PostForm, CommentsForm
from django.views.generic import (
    TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

########################################################################
# CBV FOR POSTS(post creating upodating deleting drafting)
#########################################################################


class AboutView(TemplateView):
    template_name = "blog/about.html"


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        # its kinda SQL query on the model POST.
        # returning objects like we did in FBV filtering it by
        # published_date__lte(<= lesser than equal to) timezone.now
        # so it filter by lets say the time is 17:00 it filters posts by time less than 17:00
        # and order it by -published_date
        # the dash before published_date is to make the post doesnt come from older to newer and rather
        # comes from new to old in a descending order
        # __lte is called lookups kinda stuff we use in SQL find it here more
        # https://docs.djangoproject.com/en/3.1/ref/models/lookups/
        # https://docs.djangoproject.com/en/3.1/howto/custom-lookups/
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post

# we used @login_required for FBV but we can do that for CBV so we inherit LoginRequiredMixin
# which we import from django.contrib.auth.mixins

# it has two attributes login_url and redirect_field_name
# login_url defaults to settings.LOGIN_URL
# redirect_field_name is where we wanna redirect user after loging in


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_draft_list.html'

    model = Post

    def get_queryset(self):
        # this time to see the draft list here we dont want the published_date cause we havent yet did it
        # so using lookups again  published_date__isnull=True.
        # this time we use __isnull = True which means as u know published date is gonna be null
        # and we are gonna order it by the create date descending like we did for post_list
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')


########################################################################
# FBV FOR COMMENTS AND PUBLISHING POST (comment approving  deleting)
#########################################################################

@login_required
def publish_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentsForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def approving_comment(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def remove_comment(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

wtfblog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block body %}

<h1 class="myfont">About Me</h1>
<h3 class="twofont jumbotron-fluid">
    Noob streamer who tries to work his way up towards his passsion.Average league of legends player. <br>
    Before you leave, Follow me Live streaming Down here. <br>
    <a id = "twofonttwo" href="https://www.twitch.tv/jackpersie">twitch.tv/jackpersie</a><br>
</h3>

{% endblock %}

wtfblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- bootstrap  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


    <!-- medium editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    
    
    <!-- css  -->
    <link rel="stylesheet" href="{% static 'css/base3.css' %}">
    
    
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Londrina+Solid:wght@300&display=swap" rel="stylesheet"> 

    <title>Donkey King Blog</title>
</head>
<body>
    
    <!-- nav bar for all the people -->
    <nav class="ov-nav navbar navbar-expand-lg navbar-dark bg-transparent myfont cus-navbar">
        <div class="container-fluid">
            <ul class="navbar-nav ">
                <li  class="navbar-item"><a id="login-font4" class="navbar-brand brandsize" href="{% url 'blog:post_list' %}">Home</a></li>
                <li class="navbar-item"><a id="login-font4"class="nav-link" href="{% url 'blog:about' %}">About Me</a></li>
                <li class="navbar-item"><a id="login-font4"class="nav-link" href="https://www.instagram.com">Instagram</a></li>
                <li class="navbar-item"><a id="login-font4"class="nav-link" href="https://www.youtube.com">Youtube</a></li>
                <li class="navbar-item"><a id="login-font4"class="nav-link" href="https://www.gmail.com">Gmail</a></li>
            </ul>
        </div>
    

    <!-- nav bar for all the people who are logged in. includes the above navbar too -->
    <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li clas><a id="login-font11">Hey There ! {{ user.username|title }}</a></li>
        <li class="navbar-item navbar-right"><a id="login-font5"class="nav-link" href="{% url 'blog:post_create' %}">Something Itching Your Brain {{ user.username|title }} ?</span></a></li>
        <li class="navbar-item navbar-right"><a id="login-font5"class="nav-link" href="{% url 'blog:post_drafts' %}">Your Drafts</span></a></li>
        <li class="navbar-item navbar-right"><a id="login-font5"class="nav-link" href="{% url 'logout' %}">Jump Out !</a></li>
        
        {% else %}
        <li class="navbar-item navbar-right"" ><a id="login-font6" class="nav-link" href="{% url 'login' %}">Jump In !</a></li>
        
        {% endif %}
        
    </ul>

    </nav>
    <!-- loader -->
    <div class="loader-wrapper">
        <span class="loader"><span class="loader-inner"></span>
      </div>
  
    <!-- block -->
    <div class="container-fluid block">
        <div class="row">
            <div class="col-sm-8">
                <div class="blog_posts">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>
    <script>
        $(window).on("load",function(){
          $(".loader-wrapper").fadeOut("slow");
        });
    </script>
</body>
</html>

wtfblog/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block body %}
<h1 id="comment21">New Comment</h1>
<form id = "comment23" class = "comment-form" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input id="comment22"class = " save btn btn-default" type="submit" value="Save">
    <script>var editor = new MediumEditor('.editable');</script>
</form> 
{% endblock %}

wtfblog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block body %}
<form  method="post">
    {% csrf_token %}
    <h2 id="update11">Sure u wanna remove {{object}} from the internet ?</h2>
    <input id="update21"class="btn btn-default" type="submit" value ="Trash 'em">
</form>
{% endblock %}

wtfblog/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block body %}

<h1 class="posttitle">{{post.title}}</h1> </h1>
    {% if post.published_date %} 
    <div  class = "date-postdate">
       <p id="lis22"> Thrown to Internet on {{post.published_date}} by {{post.user|title}}</p>
    </div>
    {% else %}
    <a id="det11" class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish ?</a>
    {% endif %}
    <div class="postcontent">
    <p >{{post.body|safe|linebreaks}}</p>
    </div>
<!-- https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#std:templatefilter-safe
i kinda forgot filters and custom filters, stuff we wanna change at certain point 
safe¶
Marks a string as not requiring further HTML escaping prior to output. When autoescaping is off, this filter has no effect.
whatever the fuck it means-->
{% if user.is_authenticated %}
    <a id="det1" class="  btn btn-default" href="{% url 'blog:post_update' pk=post.pk %}">Update
    </a>
    
    <a id="det1" class="btn btn-default" href="{% url 'blog:post_delete' pk=post.pk %}">Delete
    </a>
{% endif %}
    <hr>
    <a id="det2"class="btn btn-default btn-comment" href="{% url 'blog:adding_comment' pk=post.pk %}">Comment</a>
    <div id="comment" class="container-fluid">
        <h1>What the world has to say this piece of art ?</h1>
        {% for comment in post.comments.all %} <!-- comments is the related name we gave -->
        <br>
            {% if user.is_authenticated or comment.approved_comment %}
                On {{comment.created_date}}
                    {% if not comment.approved_comment %}
                    <a id="det33" class=" btn btn-danger login-font3" href="{% url 'blog:approve_comment' pk=comment.pk %}">Approve Comment</a>
                        <a id="det34" class="btn btn-danger login-font3" href="{% url 'blog:remove_comment' pk=comment.pk %}">Delete Comment</a>
                        
                    {% endif %}
            <p>{{comment.user}} Said ,</p>
            <p>{{comment.body|safe|linebreaks}}</p>
            {% endif %}
            {% empty %}
        <p>No one snooped in yet !</p>
        {% endfor %}
    </div>

{% endblock %}

wtfblog/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block body %}
    {% for post in posts %}
    <div class="post">
        <p class="date"> created: {{post.created_date|date:'d-m-Y'}}</p>
        <h1>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a>
        </h1>
        <p>{{post.body|truncatechars:200}}</p>

    </div>
{% endblock %}

wtfblog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block body %}

<h1 id="update">{{post.title}}</h1>
<form class = " update1 post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button id="update22" type="submit"class = "save btn btn-default" >Save</button>
</form>
    <script>var editor = new MediumEditor('.editable');</script>
 
{% endblock %}

wtfblog/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block body %}

<div class="makingcenter">
    <h1 class="myfont22">
        These Blogs keep on tuning in below !
    </h1>
    {% for post in post_list %}
    <div class="thepost">
        <h1><a id="list1" href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
    </div>
    <div>
        <p id="llist2">Thrown to internet on : {{post.published_date|date:"D M Y" }}</p>
    </div>
    <a id="list2" href="{% url 'blog:post_detail' pk=post.pk %}">Comments : {{post.approve_comment.count}}</a>
    {% endfor %}
</div>
{% endblock %}